*** empty log message ***

diff --git a/jollix/skripte/modules b/jollix/skripte/modules
--- a/jollix/skripte/modules
+++ b/jollix/skripte/modules
@@ -1,7 +1,7 @@
 #!/sbin/runscript
 # Copyright 1999-2002 Gentoo Technologies, Inc.
 # Distributed under the terms of the GNU General Public License, v2 or later
-# $Header: /home/xubuntu/berlios_backup/github/tmp-cvs/jollix/Repository/jollix/skripte/modules,v 1.1 2003/04/07 20:12:28 knochen Exp $
+# $Header: /home/xubuntu/berlios_backup/github/tmp-cvs/jollix/Repository/jollix/skripte/modules,v 1.2 2003/04/27 16:17:08 knochen Exp $
 
 
 depend() {
@@ -12,14 +12,14 @@ start() {
 	[ -f /proc/modules ] || return
 	[ -x /sbin/depmod ] || return
 	ebegin "Calculating module dependencies"
-	if [ -z "$CDBOOT" ]
-	then
+	#if [ -z "$CDBOOT" ]
+	#then
+	#	/usr/sbin/update-modules &>/dev/null
+	#	eend $? "Failed to calculate dependencies"
+	#else
 		/usr/sbin/update-modules &>/dev/null
-		eend $? "Failed to calculate dependencies"
-	else
-		/usr/sbin/update-modules &>/dev/null
-		eend
-	fi
+	#	eend
+	#fi
 	# Loop over every line in /etc/modules.autoload.
 	(cat /etc/modules.autoload; echo) | # make sure there is a LF at the end
 	while read module args
